#!/usr/bin/env php
<?php
require __DIR__.'/../../autoload.php';
//require __DIR__.'/vendor/autoload.php';

$app = new Symfony\Component\Console\Application('Subdivx Downloader', '1.0');
$app->add(new P4bloch\Subdivx\Download);
$app->setDefaultCommand('download');
$app->run();